"""Shared EHR prompt exports."""
from prompt.EHR_prompt.prompt_template import (
    TASK_DESCRIPTION, RESPONSE_FORMAT_ONLY_ANSWER, UNIT, REFERENCE_RANGE,
    USERPROMPT_ZERO_SHOT, USERPROMPT_FEW_SHOT, USERPROMPT_FEW_SHOT_SMART_WITH_LOGITS,
)
