CUDA_VISIBLE_DEVICES=0,1 python main.py \
    --dataset mimic4_readmission \
    --llm_name qwen3-32b-instruct \
    --seed 3407 \
    --method graph_walker \
    --icl_examples_num 3 \
    --max_tokens_each_patient 10000 \
    --use_vllm \
    --llm_responses_save_path ./llm_responses/graph_walker_v3_qwen3-14b-instruct-mimic4_readmission-period_length_24-v7_full \
    --toy_dataset \
    --toy_dataset_size_test 200 \
    --graph_walker_parallel_batch_size_for_cal_greedy_score 4 \
    --graph_walker_neighbor_num 8 \
    --vllm_max_model_len 20480 \
    --vllm_gpu_memory_utilization 0.85 \
    --period_length 24 \
    --embedding_model_name smart \
    --graph_walker_top_l_cohorts 3 \
    --graph_walker_top_k_per_cohort 3 \
    --graph_walker_n_clusters 10 \
    --graph_walker_add_smart_logits \
    --graph_walker_add_smart_logits_for_test_example \

